# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f2533255d143d30b03a88bc1908f124d"
application_url = "https://indirect-sf-services-somalia.trycloudflare.com"
embedded = true
name = "reorder"
handle = "reorder-20"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://indirect-sf-services-somalia.trycloudflare.com/auth/callback",
  "https://indirect-sf-services-somalia.trycloudflare.com/auth/shopify/callback",
  "https://indirect-sf-services-somalia.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "loilv-shop1.myshopify.com"
automatically_update_urls_on_dev = true
